import { existsSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { INSTRUMENTS } from '../domain/instruments';
import { SAMPLE_MANIFEST, SAMPLE_STEP } from './sample-manifest';
import {
  nearestSample,
  perceptualOnset,
  playbackRateFor,
  speakingStart,
  sustainLoop,
} from './sampler';

/**
 * The sample set is generated by a tool that is not run at build time, so the
 * one thing these tests must catch is drift: an instrument whose range has moved
 * beyond the notes that were actually downloaded. A missing sample is silent
 * failure — the note simply comes out at the wrong pitch.
 */

const SAMPLES_DIR = join(process.cwd(), 'public', 'samples');

/** How far a note may be shifted before stretching becomes audible. */
const MAX_SHIFT = Math.ceil(SAMPLE_STEP / 2);

describe('the sample manifest', () => {
  it('has a voice for every instrument', () => {
    for (const instrument of INSTRUMENTS) {
      expect(SAMPLE_MANIFEST[instrument.sampleSet], instrument.name).toBeDefined();
      expect(SAMPLE_MANIFEST[instrument.sampleSet].length).toBeGreaterThan(4);
    }
  });

  it('lists its notes in order, without duplicates', () => {
    for (const [set, pitches] of Object.entries(SAMPLE_MANIFEST)) {
      expect(pitches, set).toEqual([...pitches].sort((a, b) => a - b));
      expect(new Set(pitches).size, set).toBe(pitches.length);
    }
  });

  it('has the mp3 file it claims for every note', () => {
    for (const [set, pitches] of Object.entries(SAMPLE_MANIFEST)) {
      for (const midi of pitches) {
        const path = join(SAMPLES_DIR, set, `${midi}.mp3`);
        expect(existsSync(path), path).toBe(true);
        // Guards against a truncated or failed download being committed.
        expect(statSync(path).size, path).toBeGreaterThan(2000);
      }
    }
  });

  it('covers every note each instrument can be asked to play', () => {
    for (const instrument of INSTRUMENTS) {
      const pitches = SAMPLE_MANIFEST[instrument.sampleSet];
      const [low, high] = instrument.soundingRange;

      for (let midi = low; midi <= high; midi++) {
        const shift = Math.abs(nearestSample(pitches, midi) - midi);
        expect(shift, `${instrument.name} sounding ${midi}`).toBeLessThanOrEqual(MAX_SHIFT);
      }
    }
  });

});

describe('choosing and shifting a sample', () => {
  const pitches = [40, 43, 46, 49];

  it('picks the closest note', () => {
    expect(nearestSample(pitches, 43)).toBe(43);
    expect(nearestSample(pitches, 44)).toBe(43);
    expect(nearestSample(pitches, 45)).toBe(46);
  });

  it('clamps to the ends rather than failing', () => {
    expect(nearestSample(pitches, 12)).toBe(40);
    expect(nearestSample(pitches, 120)).toBe(49);
  });

  it('plays a sample at its own pitch untouched', () => {
    expect(playbackRateFor(46, 46)).toBe(1);
  });

  it('shifts by the equal-tempered ratio', () => {
    expect(playbackRateFor(47, 46)).toBeCloseTo(1.059463, 5); // up a semitone
    expect(playbackRateFor(45, 46)).toBeCloseTo(0.943874, 5); // down a semitone
    expect(playbackRateFor(58, 46)).toBeCloseTo(2, 5); // up an octave
  });
});

/**
 * The attack lead: a recording is started early by its own speak time, so the
 * note is heard on the beat rather than beginning to bloom there.
 *
 * The player's report, and the measurement that confirmed it: the tuba
 * recordings reach half level 15–60ms in and 90% up to 195ms in — slowest in
 * exactly the register an Eb bass part sounds in — while the metronome's click
 * has no bloom at all, so every low note landed a fair lag behind the beat.
 */
describe('where a recording speaks', () => {
  const rate = 44100;
  /** A buffer of `silence` seconds of nothing, then `ramp` seconds rising 0→1, then flat 1. */
  const recording = (silence: number, ramp: number, total = 1): Float32Array => {
    const samples = new Float32Array(Math.round(total * rate));
    for (let i = 0; i < samples.length; i++) {
      const t = i / rate - silence;
      samples[i] = t < 0 ? 0 : Math.min(1, ramp === 0 ? 1 : t / ramp);
    }
    return samples;
  };

  /** The measurement is in 5ms windows, so answers land on a window edge. */
  const nearTo = (actual: number, wanted: number) =>
    expect(Math.abs(actual - wanted)).toBeLessThanOrEqual(0.005);

  it('reports the moment the envelope reaches half of its peak', () => {
    // 200ms of bloom reaches half level at 100ms — the perceived landing of a
    // slow low attack, not the first molecule of sound.
    nearTo(perceptualOnset(recording(0, 0.2), rate), 0.1);
  });

  it('counts leading silence as part of the onset', () => {
    nearTo(perceptualOnset(recording(0.05, 0.2), rate), 0.15);
  });

  it('reports zero for an instant attack, and for silence', () => {
    expect(perceptualOnset(recording(0, 0), rate)).toBeCloseTo(0, 2);
    expect(perceptualOnset(new Float32Array(rate), rate)).toBe(0);
  });
});

describe('starting a note early enough to speak on the beat', () => {
  it('leads by the onset, leaving the buffer unskipped', () => {
    expect(speakingStart(0.05, 1, 10, 0)).toEqual({ when: 9.95, offset: 0 });
  });

  it('stretches the lead when the sample is slowed below its pitch', () => {
    // A sample played at half rate blooms twice as slowly, so it needs twice
    // the room; the offset stays in buffer seconds and is unaffected.
    const { when } = speakingStart(0.05, 0.5, 10, 0);
    expect(when).toBeCloseTo(9.9, 9);
  });

  it('never starts late: with no room, it skips the missed attack instead', () => {
    // The first note after the gate, or a rewind landing close ahead of a
    // note. The moment of speech stays on the beat; the bloom is clipped.
    const { when, offset } = speakingStart(0.06, 2, 10, 9.99);
    expect(when).toBe(9.99);
    // 10ms of room used, 20ms of output lead wanted: 10ms short, which at
    // double rate is 20ms of buffer skipped... in buffer seconds: (0.03-0.01)*2.
    expect(offset).toBeCloseTo((0.06 / 2 - 0.01) * 2, 9);
  });

  it('caps a pathological onset so no note runs far ahead of its neighbours', () => {
    const { when } = speakingStart(2.5, 1, 10, 0);
    expect(when).toBeCloseTo(9.9, 9); // the 100ms cap, not 2.5s
  });
});

/**
 * Looping a sample so a long note keeps sounding.
 *
 * A sample runs three seconds and a tied note in a real part runs nine, so
 * without a loop the buffer ends and the note falls silent part way through —
 * which is what a four-bar tied G did, going quiet after about two.
 */
describe('the sustain loop', () => {
  it('is a whole number of wave periods, so the wave does not jump', () => {
    /*
     * The point of the whole thing. A loop of arbitrary length restarts the
     * waveform mid-cycle, and that phase jump is a click, once per loop, for as
     * long as the note lasts. Against a real sample, snapping cut the worst
     * sample-to-sample jump from 0.028 to 0.009, where the largest jump
     * occurring naturally inside the recording is 0.007.
     */
    const midi = 47;
    const period = 1 / (440 * 2 ** ((midi - 69) / 12));
    const loop = sustainLoop(3.129, midi);

    expect(loop).not.toBeNull();
    const periods = (loop!.to - loop!.from) / period;
    expect(periods).toBeCloseTo(Math.round(periods), 9);
  });

  it('starts past the recorded attack and stops short of the end', () => {
    // Measured rather than assumed: these samples hold 98–100% of peak from
    // 0.1s to the very end, with no decay and no release tail.
    const loop = sustainLoop(3.129, 47)!;
    expect(loop.from).toBeGreaterThanOrEqual(0.1);
    expect(loop.to).toBeLessThanOrEqual(3.129 - 0.05);
  });

  it('declines a sample too short to loop cleanly', () => {
    // Below a few periods the loop is so short that any imperfection in the
    // recording's tuning beats audibly against itself. Better not to loop.
    expect(sustainLoop(0.05, 47)).toBeNull();
  });

  it('scales the loop with the pitch, since a low note has a long period', () => {
    const low = sustainLoop(3.129, 21)!;
    const high = sustainLoop(3.129, 65)!;
    // Both end inside the buffer, and the low note's loop is the coarser fit.
    expect(low.to).toBeLessThanOrEqual(3.079);
    expect(high.to).toBeLessThanOrEqual(3.079);
    expect(high.to).toBeGreaterThan(low.to);
  });
});
