import { existsSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { INSTRUMENTS } from '../domain/instruments';
import { SAMPLE_MANIFEST, SAMPLE_STEP } from './sample-manifest';
import { nearestSample, playbackRateFor, sustainLoop } from './sampler';

/**
 * The sample set is generated by a tool that is not run at build time, so the
 * one thing these tests must catch is drift: an instrument whose range has moved
 * beyond the notes that were actually downloaded. A missing sample is silent
 * failure — the note simply comes out at the wrong pitch.
 */

const SAMPLES_DIR = join(process.cwd(), 'public', 'samples');

/** How far a note may be shifted before stretching becomes audible. */
const MAX_SHIFT = Math.ceil(SAMPLE_STEP / 2);

describe('the sample manifest', () => {
  it('has a voice for every instrument', () => {
    for (const instrument of INSTRUMENTS) {
      expect(SAMPLE_MANIFEST[instrument.sampleSet], instrument.name).toBeDefined();
      expect(SAMPLE_MANIFEST[instrument.sampleSet].length).toBeGreaterThan(4);
    }
  });

  it('lists its notes in order, without duplicates', () => {
    for (const [set, pitches] of Object.entries(SAMPLE_MANIFEST)) {
      expect(pitches, set).toEqual([...pitches].sort((a, b) => a - b));
      expect(new Set(pitches).size, set).toBe(pitches.length);
    }
  });

  it('has the mp3 file it claims for every note', () => {
    for (const [set, pitches] of Object.entries(SAMPLE_MANIFEST)) {
      for (const midi of pitches) {
        const path = join(SAMPLES_DIR, set, `${midi}.mp3`);
        expect(existsSync(path), path).toBe(true);
        // Guards against a truncated or failed download being committed.
        expect(statSync(path).size, path).toBeGreaterThan(2000);
      }
    }
  });

  it('covers every note each instrument can be asked to play', () => {
    for (const instrument of INSTRUMENTS) {
      const pitches = SAMPLE_MANIFEST[instrument.sampleSet];
      const [low, high] = instrument.soundingRange;

      for (let midi = low; midi <= high; midi++) {
        const shift = Math.abs(nearestSample(pitches, midi) - midi);
        expect(shift, `${instrument.name} sounding ${midi}`).toBeLessThanOrEqual(MAX_SHIFT);
      }
    }
  });

});

describe('choosing and shifting a sample', () => {
  const pitches = [40, 43, 46, 49];

  it('picks the closest note', () => {
    expect(nearestSample(pitches, 43)).toBe(43);
    expect(nearestSample(pitches, 44)).toBe(43);
    expect(nearestSample(pitches, 45)).toBe(46);
  });

  it('clamps to the ends rather than failing', () => {
    expect(nearestSample(pitches, 12)).toBe(40);
    expect(nearestSample(pitches, 120)).toBe(49);
  });

  it('plays a sample at its own pitch untouched', () => {
    expect(playbackRateFor(46, 46)).toBe(1);
  });

  it('shifts by the equal-tempered ratio', () => {
    expect(playbackRateFor(47, 46)).toBeCloseTo(1.059463, 5); // up a semitone
    expect(playbackRateFor(45, 46)).toBeCloseTo(0.943874, 5); // down a semitone
    expect(playbackRateFor(58, 46)).toBeCloseTo(2, 5); // up an octave
  });
});

/**
 * Looping a sample so a long note keeps sounding.
 *
 * A sample runs three seconds and a tied note in a real part runs nine, so
 * without a loop the buffer ends and the note falls silent part way through —
 * which is what a four-bar tied G did, going quiet after about two.
 */
describe('the sustain loop', () => {
  it('is a whole number of wave periods, so the wave does not jump', () => {
    /*
     * The point of the whole thing. A loop of arbitrary length restarts the
     * waveform mid-cycle, and that phase jump is a click, once per loop, for as
     * long as the note lasts. Against a real sample, snapping cut the worst
     * sample-to-sample jump from 0.028 to 0.009, where the largest jump
     * occurring naturally inside the recording is 0.007.
     */
    const midi = 47;
    const period = 1 / (440 * 2 ** ((midi - 69) / 12));
    const loop = sustainLoop(3.129, midi);

    expect(loop).not.toBeNull();
    const periods = (loop!.to - loop!.from) / period;
    expect(periods).toBeCloseTo(Math.round(periods), 9);
  });

  it('starts past the recorded attack and stops short of the end', () => {
    // Measured rather than assumed: these samples hold 98–100% of peak from
    // 0.1s to the very end, with no decay and no release tail.
    const loop = sustainLoop(3.129, 47)!;
    expect(loop.from).toBeGreaterThanOrEqual(0.1);
    expect(loop.to).toBeLessThanOrEqual(3.129 - 0.05);
  });

  it('declines a sample too short to loop cleanly', () => {
    // Below a few periods the loop is so short that any imperfection in the
    // recording's tuning beats audibly against itself. Better not to loop.
    expect(sustainLoop(0.05, 47)).toBeNull();
  });

  it('scales the loop with the pitch, since a low note has a long period', () => {
    const low = sustainLoop(3.129, 21)!;
    const high = sustainLoop(3.129, 65)!;
    // Both end inside the buffer, and the low note's loop is the coarser fit.
    expect(low.to).toBeLessThanOrEqual(3.079);
    expect(high.to).toBeLessThanOrEqual(3.079);
    expect(high.to).toBeGreaterThan(low.to);
  });
});
