/**
 * Which sampled notes exist for each voice, generated by
 * tools/fetch-samples.mjs — do not edit.
 *
 * Samples live in public/samples/<voice>/<midi>.mp3. Anything between them is
 * reached by pitch-shifting the nearest one, never by more than a tone.
 *
 * FluidR3_GM by Frank Wen, CC-BY 3.0.
 */

import type { SampleSet } from '../domain/instruments';

export const SAMPLE_MANIFEST = {
  trumpet: [46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88],
  french_horn: [39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78],
  trombone: [29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68, 71, 74],
  tuba: [21, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65],
} satisfies Record<SampleSet, number[]>;

/** Largest gap the player has to cover by pitch-shifting, in semitones. */
export const SAMPLE_STEP = 3;
