import { existsSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { soundedPitch } from '../domain/fingering';
import { INSTRUMENTS, soundingFromWritten, writtenRange } from '../domain/instruments';
import { SAMPLE_MANIFEST, SAMPLE_STEP } from './sample-manifest';
import { nearestSample, playbackRateFor } from './sampler';

/**
 * The sample set is generated by a tool that is not run at build time, so the
 * one thing these tests must catch is drift: an instrument whose range has moved
 * beyond the notes that were actually downloaded. A missing sample is silent
 * failure — the note simply comes out at the wrong pitch.
 */

const SAMPLES_DIR = join(process.cwd(), 'public', 'samples');

/** How far a note may be shifted before stretching becomes audible. */
const MAX_SHIFT = Math.ceil(SAMPLE_STEP / 2);

describe('the sample manifest', () => {
  it('has a voice for every instrument', () => {
    for (const instrument of INSTRUMENTS) {
      expect(SAMPLE_MANIFEST[instrument.sampleSet], instrument.name).toBeDefined();
      expect(SAMPLE_MANIFEST[instrument.sampleSet].length).toBeGreaterThan(4);
    }
  });

  it('lists its notes in order, without duplicates', () => {
    for (const [set, pitches] of Object.entries(SAMPLE_MANIFEST)) {
      expect(pitches, set).toEqual([...pitches].sort((a, b) => a - b));
      expect(new Set(pitches).size, set).toBe(pitches.length);
    }
  });

  it('has the mp3 file it claims for every note', () => {
    for (const [set, pitches] of Object.entries(SAMPLE_MANIFEST)) {
      for (const midi of pitches) {
        const path = join(SAMPLES_DIR, set, `${midi}.mp3`);
        expect(existsSync(path), path).toBe(true);
        // Guards against a truncated or failed download being committed.
        expect(statSync(path).size, path).toBeGreaterThan(2000);
      }
    }
  });

  it('covers every note each instrument can be asked to play', () => {
    for (const instrument of INSTRUMENTS) {
      const pitches = SAMPLE_MANIFEST[instrument.sampleSet];
      const [low, high] = instrument.soundingRange;

      for (let midi = low; midi <= high; midi++) {
        const shift = Math.abs(nearestSample(pitches, midi) - midi);
        expect(shift, `${instrument.name} sounding ${midi}`).toBeLessThanOrEqual(MAX_SHIFT);
      }
    }
  });

  it('covers the wrong notes too, not just the right ones', () => {
    // In "play what I finger" mode a wrong fingering lands on a neighbouring
    // harmonic, which can fall outside anything the exercise would ask for. Those
    // notes still have to sound, so they still need samples near them.
    for (const instrument of INSTRUMENTS) {
      const pitches = SAMPLE_MANIFEST[instrument.sampleSet];

      for (const clef of ['treble', 'bass'] as const) {
        if (instrument.transposition[clef] === undefined) continue;
        const [low, high] = writtenRange(instrument, clef);

        for (let written = low; written <= high; written++) {
          const target = soundingFromWritten(written, instrument, clef);
          for (let mask = 0; mask < 8; mask++) {
            const sounded = soundedPitch(mask, target, instrument);
            const shift = Math.abs(nearestSample(pitches, sounded) - sounded);
            expect(
              shift,
              `${instrument.name} ${clef}: written ${written} fingered ${mask} sounds ${sounded}`,
            ).toBeLessThanOrEqual(MAX_SHIFT + SAMPLE_STEP);
          }
        }
      }
    }
  });
});

describe('choosing and shifting a sample', () => {
  const pitches = [40, 43, 46, 49];

  it('picks the closest note', () => {
    expect(nearestSample(pitches, 43)).toBe(43);
    expect(nearestSample(pitches, 44)).toBe(43);
    expect(nearestSample(pitches, 45)).toBe(46);
  });

  it('clamps to the ends rather than failing', () => {
    expect(nearestSample(pitches, 12)).toBe(40);
    expect(nearestSample(pitches, 120)).toBe(49);
  });

  it('plays a sample at its own pitch untouched', () => {
    expect(playbackRateFor(46, 46)).toBe(1);
  });

  it('shifts by the equal-tempered ratio', () => {
    expect(playbackRateFor(47, 46)).toBeCloseTo(1.059463, 5); // up a semitone
    expect(playbackRateFor(45, 46)).toBeCloseTo(0.943874, 5); // down a semitone
    expect(playbackRateFor(58, 46)).toBeCloseTo(2, 5); // up an octave
  });
});
