/**
 * Bakes the handful of music glyphs we need out of the Bravura font and into
 * src/render/glyphs.ts as plain SVG path data.
 *
 * This is an authoring step, not a build step. Running it is only necessary if
 * the glyph set changes — the generated file is committed, so the app itself
 * ships with no font file, no font loading, and no dependency on opentype.js.
 *
 * To re-run:
 *   npm i -D opentype.js
 *   curl -fsSLO https://github.com/steinbergmedia/bravura/raw/master/redist/otf/Bravura.otf
 *   node tools/extract-glyphs.mjs Bravura.otf
 *   npm uninstall opentype.js
 *
 * Bravura is (c) Steinberg Media Technologies GmbH, SIL Open Font License 1.1.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import opentype from 'opentype.js';

const { parse } = opentype;

/**
 * SMuFL sizes everything in stave spaces, where one stave space is 250 font
 * units. Asking opentype for a font size of 4 therefore yields path data
 * already measured in stave spaces, with y pointing down as canvas expects.
 */
const STAVE_SPACES_PER_EM = 4;
const PRECISION = 4;

const GLYPHS = {
  gClef: 0xe050,
  fClef: 0xe062,
  accidentalFlat: 0xe260,
  accidentalNatural: 0xe261,
  accidentalSharp: 0xe262,
  noteheadWhole: 0xe0a2,
  noteheadHalf: 0xe0a3,
  noteheadBlack: 0xe0a4,
  flag8thUp: 0xe240,
  flag8thDown: 0xe241,
  flag16thUp: 0xe242,
  flag16thDown: 0xe243,
  flag32ndUp: 0xe244,
  flag32ndDown: 0xe245,
  restWhole: 0xe4e3,
  restHalf: 0xe4e4,
  restQuarter: 0xe4e5,
  rest8th: 0xe4e6,
  rest16th: 0xe4e7,
  rest32nd: 0xe4e8,
  augmentationDot: 0xe1e7,
  timeSig0: 0xe080,
  timeSig1: 0xe081,
  timeSig2: 0xe082,
  timeSig3: 0xe083,
  timeSig4: 0xe084,
  timeSig5: 0xe085,
  timeSig6: 0xe086,
  timeSig7: 0xe087,
  timeSig8: 0xe088,
  timeSig9: 0xe089,
};

const fontPath = process.argv[2] ?? 'Bravura.otf';
const font = parse(readFileSync(fontPath).buffer);

const entries = [];
for (const [name, codepoint] of Object.entries(GLYPHS)) {
  const glyph = font.charToGlyph(String.fromCodePoint(codepoint));
  if (!glyph || glyph.index === 0) {
    throw new Error(`${name} (U+${codepoint.toString(16)}) missing from ${fontPath}`);
  }
  const path = glyph.getPath(0, 0, STAVE_SPACES_PER_EM);
  const { x1, y1, x2, y2 } = path.getBoundingBox();
  entries.push({
    name,
    codepoint,
    d: path.toPathData(PRECISION),
    bbox: [x1, y1, x2, y2].map((v) => Number(v.toFixed(PRECISION))),
  });
}

const body = entries
  .map(
    ({ name, codepoint, d, bbox }) =>
      `  ${name}: {\n` +
      `    codepoint: 0x${codepoint.toString(16)},\n` +
      `    bbox: { left: ${bbox[0]}, top: ${bbox[1]}, right: ${bbox[2]}, bottom: ${bbox[3]} },\n` +
      `    d: '${d}',\n` +
      `  },`,
  )
  .join('\n');

const output = `/**
 * Music glyph outlines, generated by tools/extract-glyphs.mjs — do not edit.
 *
 * Paths are measured in stave spaces (one stave space = 1 unit) with y pointing
 * down, so they can be drawn straight onto a canvas by translating to the glyph
 * origin and scaling by the stave space size in pixels.
 *
 * Outlines from Bravura, (c) Steinberg Media Technologies GmbH,
 * SIL Open Font License 1.1.
 */

export interface Glyph {
  codepoint: number;
  bbox: { left: number; top: number; right: number; bottom: number };
  d: string;
}

export const GLYPHS = {
${body}
} satisfies Record<string, Glyph>;

export type GlyphName = keyof typeof GLYPHS;

const cache = new Map<GlyphName, Path2D>();

/** Path2D instances are reusable and cheap to draw; build each glyph once. */
export function glyphPath(name: GlyphName): Path2D {
  let path = cache.get(name);
  if (!path) {
    path = new Path2D(GLYPHS[name].d);
    cache.set(name, path);
  }
  return path;
}

export function glyphWidth(name: GlyphName): number {
  const { left, right } = GLYPHS[name].bbox;
  return right - left;
}

/**
 * Draws a glyph with its origin at (x, y), scaled so one stave space is
 * \`staveSpace\` pixels.
 */
export function drawGlyph(
  ctx: CanvasRenderingContext2D,
  name: GlyphName,
  x: number,
  y: number,
  staveSpace: number,
): void {
  ctx.save();
  ctx.translate(x, y);
  ctx.scale(staveSpace, staveSpace);
  ctx.fill(glyphPath(name));
  ctx.restore();
}
`;

writeFileSync(new URL('../src/render/glyphs.ts', import.meta.url), output);
console.log(`Wrote ${entries.length} glyphs to src/render/glyphs.ts`);
