/**
 * Pulls recorded brass samples out of the FluidR3_GM soundfont and writes the
 * subset this app actually needs into public/samples/.
 *
 * An authoring step, like the other two tools. The output is committed, so
 * building the app needs no network access and no dependencies.
 *
 *   node tools/fetch-samples.mjs
 *
 * Samples from FluidR3_GM by Frank Wen, packaged by gleitz/midi-js-soundfonts.
 * Released under Creative Commons Attribution 3.0 — attribution ships in
 * README.md and in the app's settings screen.
 */

import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = join(ROOT, 'public', 'samples');
const SOURCE = 'https://gleitz.github.io/midi-js-soundfonts/FluidR3_GM';

/**
 * One General MIDI voice per brass family, with the sounding range it has to
 * cover.
 *
 * The ranges are padded well past each instrument's own compass because in
 * "play what I finger" mode a wrong fingering lands on a neighbouring harmonic,
 * which can fall outside the notes the exercise would ever ask for.
 */
const SETS = {
  trumpet: { low: 46, high: 88 },
  french_horn: { low: 39, high: 78 },
  trombone: { low: 29, high: 74 },
  tuba: { low: 17, high: 64 },
};

/**
 * Every third semitone. The player pitch-shifts by at most one semitone either
 * way, which is far too little to sound artificial, and it cuts the download to
 * a third of the full chromatic set.
 */
const STEP = 3;

const LETTERS = { C: 0, D: 2, E: 4, F: 5, G: 7, A: 9, B: 11 };

function midiOf(name) {
  const match = /^([A-G])(#|b)?(-?\d+)$/.exec(name);
  if (!match) return null;
  const alter = match[2] === '#' ? 1 : match[2] === 'b' ? -1 : 0;
  return (Number(match[3]) + 1) * 12 + LETTERS[match[1]] + alter;
}

async function fetchSet(name) {
  const response = await fetch(`${SOURCE}/${name}-mp3.js`);
  if (!response.ok) throw new Error(`${name}: HTTP ${response.status}`);
  const source = await response.text();

  const samples = new Map();
  const pattern = /"([A-G][#b]?-?\d+)":\s*"data:audio\/mp3;base64,([^"]+)"/g;
  for (const [, note, base64] of source.matchAll(pattern)) {
    const midi = midiOf(note);
    if (midi !== null) samples.set(midi, base64);
  }
  if (samples.size === 0) throw new Error(`${name}: no samples found`);
  return samples;
}

const manifest = {};
let totalBytes = 0;

for (const [name, range] of Object.entries(SETS)) {
  const available = await fetchSet(name);
  const keys = [...available.keys()].sort((a, b) => a - b);
  const lowest = keys[0];
  const highest = keys[keys.length - 1];

  const directory = join(OUTPUT, name);
  rmSync(directory, { recursive: true, force: true });
  mkdirSync(directory, { recursive: true });

  const written = [];
  // One step past the top, so the highest notes are still bracketed by samples
  // rather than being reached by shifting up from well below them.
  for (let midi = range.low; midi <= range.high + STEP - 1; midi += STEP) {
    // The source does not go below A0 or above C8; clamp rather than skip, so
    // the extremes are still covered by their nearest real recording.
    const nearest = Math.min(Math.max(midi, lowest), highest);
    const closest = keys.reduce((best, key) =>
      Math.abs(key - nearest) < Math.abs(best - nearest) ? key : best,
    );
    if (written.includes(closest)) continue;

    const bytes = Buffer.from(available.get(closest), 'base64');
    writeFileSync(join(directory, `${closest}.mp3`), bytes);
    written.push(closest);
    totalBytes += bytes.length;
  }

  manifest[name] = written.sort((a, b) => a - b);
  console.log(
    `${name}: ${written.length} samples, MIDI ${written[0]}-${written[written.length - 1]}`,
  );
}

const body = Object.entries(manifest)
  .map(([name, midi]) => `  ${name}: [${midi.join(', ')}],`)
  .join('\n');

writeFileSync(
  join(ROOT, 'src', 'audio', 'sample-manifest.ts'),
  `/**
 * Which sampled notes exist for each voice, generated by
 * tools/fetch-samples.mjs — do not edit.
 *
 * Samples live in public/samples/<voice>/<midi>.mp3. Anything between them is
 * reached by pitch-shifting the nearest one, never by more than ${STEP === 3 ? 'a tone' : STEP + ' semitones'}.
 *
 * FluidR3_GM by Frank Wen, CC-BY 3.0.
 */

import type { SampleSet } from '../domain/instruments';

export const SAMPLE_MANIFEST = {
${body}
} satisfies Record<SampleSet, number[]>;

/** Largest gap the player has to cover by pitch-shifting, in semitones. */
export const SAMPLE_STEP = ${STEP};
`,
);

console.log(`Total ${(totalBytes / 1024).toFixed(0)} KB across ${Object.keys(SETS).length} voices`);
